### ISSUE TITLE
Set up vetting

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/depreman#3]
- [x] [licensee](https://www.npmjs.com/package/licensee) (ca84b6e8dfc5f81037f2f3d1e1de11a59c2ed0d7)
- [x] [lockfile-lint](https://www.npmjs.com/package/lockfile-lint) (e4ab16629e7702ae8b77c7a409f06d05e825fcae)
- [x] [publint](https://www.npmjs.com/package/publint) (ca84b6e8dfc5f81037f2f3d1e1de11a59c2ed0d7)
- [x] [ls-engines](https://www.npmjs.com/package/ls-engines) (093f5b3f1c417930a86e47601081ccfc0713b40f)
